// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgocuimgofnzkqxjalyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnb2N1aW1nb2ZuemtxeGphbHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NjMzMzQsImV4cCI6MjA5MDMzOTMzNH0.DuJGt9QVvZZqVAaz6VdpVuzJ_gTMt2pfGdW_s1fOwy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});